[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[project]
name = "toolbox"
version = "2.0.0"
description = "Python scriptlets"
authors = [
    {name = "George Boukeas", email = "george.boukeas@canonical.com"},
]
requires-python = ">=3.8"
dependencies = [
    "fabric>=3.2.2",
    "snapstore @ ../snapstore"
]
[project.scripts]
# snap_connections = "toolbox.snap_connections:main"
# snap_state = "toolbox.snap_state:main"
_run = "toolbox.cli.run:main"
run = "toolbox.cli.run:main"
wait-for-ssh = "toolbox.cli.wait_for_ssh:main"
wait_for_ssh = "toolbox.cli.wait_for_ssh:main"
wait-for-packages-complete = "toolbox.cli.wait_for_packages_complete:main"
wait_for_packages_complete = "toolbox.cli.wait_for_packages_complete:main"
wait-for-snap-changes = "toolbox.cli.wait_for_snap_changes:main"
wait_for_snap_changes = "toolbox.cli.wait_for_snap_changes:main"

[project.optional-dependencies]
dev = ["pytest"]